### ISSUE TITLE
Home page for Form Creatiors

### ISSUE THREAD

**Issue by e-aakash** [pulsejet/cerium#3]
**Feature Request**
It would be easier for user if there is a home page listing all the forms created him. Saves the user from "saving" the links somewhere else.

**Comment by pulsejet** [comment]
This would be *very* nice to have, but we'll have to think a bit about the design unless we're going to continue copying Google forms blatantly (and this won't be easy either in this case).

**Comment by e-aakash** [comment]
Closed by https://github.com/pulsejet/cerium/pull/4
